### ISSUE TITLE
Issue with postgresql

### ISSUE THREAD

**Issue by torticolix** [swisscom/cleanerversion#153]
Hi all !

I tried to use cleanerversion with mptt.
Seems to work fine with sqlite until I switched to postgresql :

Anyone an idea ?

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "versions_tests_chainstore" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 223, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/lib/python3.6/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in send
    for receiver in self._live_receivers(sender)
  File "/usr/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/lib/python3.6/site-packages/versions_tests/apps.py", line 20, in index_adjustments
    create_current_version_unique_indexes(sender.name, using)
  File "/usr/lib/python3.6/site-packages/versions/util/postgresql.py", line 142, in create_current_version_unique_indexes
    % (index_name, table_name, ','.join(columns)))
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "versions_tests_chainstore" does not exist

**Comment by maennel** [comment]
Hey @Torticolix, it looks like migrations have not been applied at some
point.
Can you please describe the steps how you got to this point?
Thank you.

**Comment by torticolix** [comment]
I got this problem by trying to make an existing project versionnable.
My tests worked fine in a virtual environment but not on my development system (without venv)
I created a new project, only added mptt and cleanerversion to INSTALLED APPS. migrate works with sqlite but got this above with a newly created PostgreSQL database

**Comment by maennel** [comment]
So, my assumption is that the command that you are running is ``python
manage.py migrate`` and it fails with the above error message.
With the current information it is difficult to say what is wrong. Maybe
the settings(.py) used for the migration could help. Can you please add
them to the thread?
What seems a bit strange to me is why does migrate try to act the test
models (from versions_tests)? ``versions_tests`` shouldn't be required in
your ``INSTALLED_APPS`` to run your app...
Just fyi, for the next 2 weeks I don't have access to a PC to debug, so I
may not be very responsive...

**Comment by torticolix** [comment]
I tried from scratch in a virtual environment
Here step by step what I did :

pipenv install django django-extensions werkzeug
pipenv install django-mptt cleanerversions
pipenv install psycopg2

pipenv shell
django-admin startproject myapp
cd myapp

added in INSTALLED_APPS of settings.py
    'django_extensions',
    'mptt',
    'versions_tests',

1st try (sqlite) : 
./manage.py makemigrations
./manage.py migrate
... and all went fine

2nd try postgresql :
createdb myapp

in settings.py, changed database to
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'myapp',
        'USER': 'chris',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

./manage.py makemigrations
./manage.py migrate
and... bing...
django.db.utils.ProgrammingError: relation "versions_tests_chainstore" does not exist

I'm not an expert wether in python not in django... but I think i'm not so bad doing that

**Comment by maennel** [comment]
Hey @Torticolix, there was no offense intended. Sorry if I expressed myself
in a way that gave you that impression..

Back to business: Thanks for providing more details. I think you should be
able to remove ``versions_tests`` from INSTALLED_APPS. With that,
migrations should pass.
Cleanerversion does some additional things if it detects you're using
PostgeSQL, like adding additional indexes etc. This seems to be the root
cause here. But since you don't need the testing models, we should be able
to work around the error.
Let me know what happens...

versions_tests models are migrated to the DB at every test run on
travis-ci. So, I don't understand the problem happening in your case fully
yet. However, I will have time to dig deeper in two weeks time only..

**Comment by maennel** [comment]
Oh, and please add ``versions`` to your INSTALLED_APPS.

Looking forward to your feedback.

**Comment by torticolix** [comment]
Yep Maennel, migration passed !
Had no time to test deeper, but it's a good start for me 😁. Thanks for the help
