### ISSUE TITLE
migrations not working properly

### ISSUE THREAD

**Issue by brki** [swisscom/cleanerversion#53]
Encountered with python 2.7.9, Django 1.7.4 and CleanerVersion 1.3.3  - 1.4.1.  Did not try 1.3.2 or earlier.

How to reproduce (this sequence is based on the process described in the Django tutorial https://docs.djangoproject.com/en/1.7/intro/tutorial01/ )
```
django-admin.py startproject foo
cd foo
./manage.py migrate
./manage.py startapp bar
```
* add bar in foo.settings.INSTALLED_APPS
* edit bar/models.py so that it looks like this:
```
from django.db import models
import versions.models as vmodels

class City(vmodels.Versionable):
    name = models.CharField(max_length=40)

class Office(vmodels.Versionable):
    name = models.CharField(max_length=40)
    city = vmodels.VersionedForeignKey(City)

class Employee(vmodels.Versionable):
    name = models.CharField(max_length=40)
    offices = vmodels.VersionedManyToManyField(Office, related_name='employees')
```

Then run:
```
./manage.py makemigrations bar && ./manage.py migrate
```
This gives following output:
```
Migrations for 'bar':
  0001_initial.py:
    - Create model City
    - Create model Employee
    - Create model Office
    - Alter unique_together for office (1 constraint(s))
    - Add field offices to employee
    - Alter unique_together for employee (1 constraint(s))
    - Alter unique_together for city (1 constraint(s))

Operations to perform:
  Apply all migrations: admin, contenttypes, bar, auth, sessions
Running migrations:
  Applying bar.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/cv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/venv/cv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/cv/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/venv/cv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/venv/cv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/venv/cv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/venv/cv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/venv/cv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/venv/cv/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 37, in database_forwards
    field,
  File "/venv/cv/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 176, in add_field
    self._remake_table(model, create_fields=[field])
  File "/venv/cv/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 144, in _remake_table
    self.quote_name(model._meta.db_table),
  File "/venv/cv/lib/python2.7/site-packages/django/db/backends/schema.py", line 102, in execute
    cursor.execute(sql, params)
  File "/venv/cv/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/venv/cv/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/venv/cv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/venv/cv/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/venv/cv/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table bar_employee__new has no column named offices
```

**Comment by brki** [comment]
Works fine now, some commit must have fixed the problem :)

**Comment by peterfarrell** [comment]
Yay!
